helmDefaults:
  kubeContext: gke_nifty-depth-285109_asia-southeast2-a_cluster-1

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami 
  - name: traefik 
    url: https://helm.traefik.io/traefik


releases:
  - name: wiben-site
    chart: bitnami/nginx
    values:
    - "deploy/wiben-site/values.yaml"
  - name: traefik
    chart: traefik/traefik
    values:
    - "deploy/traefik/values.yaml"